### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by rockymeza** [fusionbox/django-widgy#54]
We need at least a quickstart.

**Comment by PhilipGarnero** [comment]
Is it possible to get an other quickstart guide for people not using mezzanine ?

For people using a simple django setup it is quite a pain in the head to figure out which package is needed, which is not, which settings are linked to mezzanine, which are not...
I'm gonna give it a try anyway and maybe write a second documentation page once I'm done.

**Comment by gavinwahl** [comment]
Hi Philip,

I'm working on this guide here: https://github.com/fusionbox/django-widgy/pull/304

Is that helpful for you?

Thanks

**Comment by PhilipGarnero** [comment]
Hi !
That'll help a lot !
Actually, I need to get rig of a lot of things I will not need in widgy (like compressor for instance, I'm using pipeline).
I think I'm gonna go for a fork and modify it to integrate with my setup for now.
I'll let you know if I manage to make things a bit more modular.

PS: I think this is app wonderful, thanks for working on it

**Comment by gavinwahl** [comment]
Widgy relies pretty heavily on compressor to compile the scss for its backend. I think it'll be difficult to replace with pipeline. I don't see any reason why widgy can't use compressor while your frontend uses pipeline, though.

I'd really love to get your changes into mainline widgy instead of forking, so do you mind keeping us up to date with your work? We can offer help if you run into any problems.

> PS: I think this is app wonderful

Thanks!
